name: The Garment Factory
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Navigation
navigation:
  - title: Office
    url: /office
  - title: Retail
    url: /retail/
  - title: Location
    url: /location/
  - title: Info
    url: /info/
  # - title: Downloads
  #   url: /downloads/


permalink: pretty

button_classes: bg-black white f4 pa3 underline dashed hover-bg-dark-gray link tracked-mega tc

downloads:
  - title: Office Brochure
    link: office-brochure.pdf
  - title: Floor Plans
    link: floor-plans.pdf
  - title: Space Plans
    link: space-plans.pdf
