name: The Garment Factory
# markdown: redcarpet
# highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
tagline: "Where Ideas Are Made"
description: "Office and retail space in Glasgow's Merchant City"

website: http://thegarmentfactory.co

email: rpittaway@castleforgepartners.com

# Navigation
navigation:
  - title: Office
    url: /office
  - title: Retail
    url: /retail/
  - title: Location
    url: /location/
  - title: Info
    url: /info/
  # - title: Downloads
  #   url: /downloads/


permalink: pretty

button_classes: fl bg-black white f5 f4-ns pa3 underline dashed dashed-yellow hover-bg-dark-gray link tracked tc

yellow_button_classes: fl bg-yellow black mt3 f5 f4-ns pa3 underline dashed dashed-white link hover-bg-gold tracked

brochure: TGF-Office-Brochure.pdf

downloads:
  - title: Office Brochure
    link: TGF-Office-Brochure.pdf
  # - title: Floor Plans
  #   link: floor-plans.pdf
  # - title: Space Plans
  #   link: space-plans.pdf

gems:
  - jekyll-sitemap
